# Generated by Django 5.0.7 on 2024-07-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_rename_subscription_subscription_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
