# Generated by Django 5.0.7 on 2024-08-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_subscription_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="comment",
            field=models.CharField(default="", max_length=50),
        ),
    ]
